apiVersion: v1
kind: Service
metadata:
  name: water-meter
  namespace: water-meter
spec:
  type: ClusterIP
  selector:
    app: water-meter
  ports:
    - name: http
      port: 8080
      targetPort: http
