loki:
  compactor:
    retention_enabled: true
    retention_delete_delay: 2h
    retention_delete_worker_count: 150
    compaction_interval: 10m
    delete_request_cancel_period: 24h
    retention_period: 168h  # 7 days

compactor:
  replicas: 1