loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
  rulerConfig:
    storage:
      type: local

gateway:
  service:
    type: NodePort
    nodePort: 31000

read:
  persistence:
    storageClass: longhorn
    storageClassname: longhorn

singleBinary:
  replicas: 1
  persistence:
    storageClass: longhorn
    storageClassname: longhorn

write:
  persistence:
    storageClass: longhorn
    storageClassname: longhorn
