ingress:
  enabled: true
  hosts:
    - metabase.grant.dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik

  tls:
    - hosts:
        - metabase.grant.dev
      secretName: metabase-grant-dev-tls

database:
  type: mysql
  host: mariadb-primary
  port: 3306
  dbname: metabase
  username: root
  existingSecret: metabase-mariadb
  existingSecretPasswordKey: password
