apiVersion: v1
kind: Namespace
metadata:
  name: minecraft
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-claim
  namespace: minecraft
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
  namespace: minecraft
spec:
  loadBalancerIP: 192.168.150.10
  ports:
  - port: 25565
    targetPort: 25565
  selector:
    app: minecraft
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-deploy
  namespace: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server
        volumeMounts:
        - name: minecraft-volume
          mountPath: "/data"
        ports:
        - containerPort: 25565
        env:
        - name: EULA
          value: "TRUE"
        - name: TYPE
          value: "SPONGEVANILLA"
      volumes:
      - name: minecraft-volume
        persistentVolumeClaim:
          claimName: minecraft-claim

