# exposes the RDS instance to the LOCAL cluster.
# this is step 2 outlined in "kubernetes and tailscale" doc
# RDS is already exposed to tailnet via the production k8s cluster (see rds.yml in truelist-k8s/production)
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: default-truelist-prod-db.rya-scala.ts.net
  name: rds-production
spec:
  externalName: rds-prod
  type: ExternalName
