apiVersion: v1
kind: Service
metadata:
  name: prometheus-sevice
  namespace: prometheus
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  ports:
  - port: 80
    targetPort: 9090
  selector:
    app: prometheus
    component: server
  type: LoadBalancer

