# Exposes the prometheus exporter service (running on the truelist production EKS cluster nodes) to the tailscale network
# so that the local k8s cluster (running prometheus) can scrape the metrics from the exporter service.
apiVersion: v1
kind: Service
metadata:
  namespace: observability
  annotations:
    tailscale.com/tailnet-ip: 100.68.59.122
  name: truelist-prod-prometheus-exporter-node-1
  labels:
    monitoring: node-health
spec:
  externalName: placeholder   # any value - will be overwritten by operator
  type: ExternalName
  ports:
  - name: metrics
    port: 9100
    targetPort: 9100
---
apiVersion: v1
kind: Service
metadata:
  namespace: observability
  annotations:
    tailscale.com/tailnet-ip: 100.120.218.120
  name: truelist-prod-prometheus-exporter-node-2
  labels:
    monitoring: node-health
spec:
  externalName: placeholder   # any value - will be overwritten by operator
  type: ExternalName
  ports:
  - name: metrics
    port: 9100
    targetPort: 9100
---
apiVersion: v1
kind: Service
metadata:
  namespace: observability
  annotations:
    tailscale.com/tailnet-ip: 100.127.165.111
  name: truelist-prod-prometheus-exporter-node-3
  labels:
    monitoring: node-health
spec:
  externalName: placeholder   # any value - will be overwritten by operator
  type: ExternalName
  ports:
  - name: metrics
    port: 9100
    targetPort: 9100
---
apiVersion: v1
kind: Service
metadata:
  namespace: observability
  annotations:
    tailscale.com/tailnet-ip: 100.118.98.91
  name: truelist-prod-prometheus-exporter-node-4
  labels:
    monitoring: node-health
spec:
  externalName: placeholder   # any value - will be overwritten by operator
  type: ExternalName
  ports:
  - name: metrics
    port: 9100
    targetPort: 9100
---
apiVersion: v1
kind: Service
metadata:
  namespace: observability
  annotations:
    tailscale.com/tailnet-ip: 100.127.111.3
  name: truelist-prod-prometheus-exporter-node-5
  labels:
    monitoring: node-health
spec:
  externalName: placeholder   # any value - will be overwritten by operator
  type: ExternalName
  ports:
  - name: metrics
    port: 9100
    targetPort: 9100
