persistentVolumeClaim:
  enabled: true
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
  storageClass: "nfs-client"

serviceTCP:
  loadBalancerIP: 192.168.150.1
  type: LoadBalancer
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc

serviceUDP:
  loadBalancerIP: 192.168.150.1
  type: LoadBalancer
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc

ingress:
  enabled: true
