service:
  type: NodePort
  port: 8124

securityContext:
  privileged: true

persistence:
  enabled: true
  storageClass: "longhorn"
  accessMode: "ReadWriteOnce"
  existingVolume: home-assistant-home-assistant-0

additionalVolumes:
  - hostPath:
      path: >-
        /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230803102536-if00
      type: CharDevice
    name: usb

additionalMounts:
  - mountPath: /dev/ttyACM0
    name: usb
