---
apiVersion: v1
kind: Service
metadata:
  name: immich-postgres
  namespace: immich
spec:
  clusterIP: None
  selector:
    app: immich-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: immich-postgres
  namespace: immich
spec:
  serviceName: immich-postgres
  replicas: 1
  selector:
    matchLabels:
      app: immich-postgres
  template:
    metadata:
      labels:
        app: immich-postgres
      annotations:
        backup.velero.io/backup-volumes-excludes: data
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3s-node-3
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      securityContext:
        fsGroup: 999
      containers:
        - name: postgres
          image: ghcr.io/immich-app/postgres:17-vectorchord1.1.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgres
              containerPort: 5432
          envFrom:
            - secretRef:
                name: immich-postgres
          env:
            - name: DB_STORAGE_TYPE
              value: "SSD"
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: "1"
              memory: 2Gi
            limits:
              cpu: "4"
              memory: 6Gi
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "immich", "-d", "immich"]
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "immich", "-d", "immich"]
            initialDelaySeconds: 60
            periodSeconds: 30
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: immich-postgres-data
