apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cliproxyapi-auth
  namespace: cliproxyapi
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
