apiVersion: v1
kind: Pod
metadata:
  name: minecraft-world-backup
  namespace: minecraft-new
spec:
  restartPolicy: Never
  containers:
  - name: minecraft-world-backup
    image: gammons1/minecraft-world-backup:7
    volumeMounts:
    - name: minecraft-volume
      mountPath: "/data"
    command: ['sh','-c','sleep infinity']
  volumes:
  - name: minecraft-volume
    persistentVolumeClaim:
      claimName: minecraft-claim-new-local
