apiVersion: apps/v1
kind: Deployment
metadata:
  name: ffmpeg-streamer
  namespace: tv-channel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ffmpeg-streamer
  template:
    metadata:
      labels:
        app: ffmpeg-streamer
    spec:
      volumes:
        - name: media-storage
          persistentVolumeClaim:
            claimName: media-pvc
        - name: script-volume
          configMap:
            name: shuffle-script
      containers:
        - name: ffmpeg-streamer
          image: ruby:3.2
          command: ["/bin/sh", "-c"]
          args:
            - |
              apt-get update && apt-get install -y ffmpeg;

              while true; do
                ruby /scripts/select_one_file.rb;

                FILE=$(cat /mnt/media/current_file.txt)
                echo "Streaming file: $FILE"

                ffmpeg -re -fflags +genpts -i "$FILE" \
                  -c:v libx264 -preset veryfast -b:v 2500k -maxrate 2500k -bufsize 5000k \
                  -c:a aac -b:a 128k -ar 48000 \
                  -f flv rtmp://192.168.10.2:31935/live/stream
              done;
          volumeMounts:
            - mountPath: /mnt/media
              name: media-storage
            - mountPath: /scripts
              name: script-volume
          resources:
            limits:
              cpu: "4"
              memory: "2Gi"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shuffle-script
  namespace: tv-channel
data:
  select_one_file.rb: |
    #!/usr/bin/env ruby
    files = Dir.glob("/mnt/media/**/*.{mkv,mp4,webm}").shuffle
    File.open("/mnt/media/current_file.txt", "w") do |file|
      file.puts files.first
    end

---
apiVersion: v1
kind: Service
metadata:
  name: ffmpeg-rtmp
  namespace: tv-channel
spec:
  type: ClusterIP
  ports:
    - name: rtmp
      port: 1935
      targetPort: 31935
      protocol: TCP
  selector:
    app: ffmpeg-streamer

