apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-rtmp-config
  namespace: tv-channel
data:
  nginx.conf: |
    worker_processes auto;
    events {
        worker_connections 1024;
    }
    rtmp {
        server {
            listen 1935;
            chunk_size 4096;

            application live {
                live on;
                hls on;
                hls_path /mnt/hls;
                hls_fragment 6s;
                hls_playlist_length 30s;
                hls_type live;
                hls_continuous on;
                hls_sync 100ms;
                hls_fragment_naming system;
                hls_nested on;
                hls_cleanup on;
                hls_variant _low BANDWIDTH=800000;
                hls_variant _mid BANDWIDTH=1400000;
                hls_variant _high BANDWIDTH=2500000;
                allow publish all;
                allow play all;
            }
        }
    }
    http {
        server {
            listen 8080;

            location /hls {
                types {
                    application/vnd.apple.mpegurl m3u8;
                    video/mp2t ts;
                }
                root /mnt;
                add_header Cache-Control no-cache;
                add_header Access-Control-Allow-Origin *;
            }
        }
    }

