apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rtmp
  namespace: tv-channel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-rtmp
  template:
    metadata:
      labels:
        app: nginx-rtmp
    spec:
      volumes:
        - name: hls-storage
          persistentVolumeClaim:
            claimName: media-pvc
        - name: config-volume  # ✅ New volume for custom config
          configMap:
            name: nginx-rtmp-config
      containers:
        - name: nginx-rtmp
          image: tiangolo/nginx-rtmp
          volumeMounts:
            - mountPath: /mnt/hls
              name: hls-storage
            - mountPath: /etc/nginx/nginx.conf  # ✅ Mount the custom config
              subPath: nginx.conf
              name: config-volume
          ports:
            - containerPort: 1935  # RTMP port
            - containerPort: 8080  # HTTP for HLS
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-rtmp
  namespace: tv-channel
spec:
  selector:
    app: nginx-rtmp
  ports:
    - name: rtmp
      protocol: TCP
      port: 1935
      targetPort: 1935
      nodePort: 31935
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32080
  type: NodePort

