apiVersion: v1
kind: Service
metadata:
  name: metabase-ip-service
  namespace: ultralist
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: metabase
  type: LoadBalancer
