apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.50.1-192.168.50.255
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: main-pool-advertisement
  namespace: metallb-system
