---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-claim
  namespace: minecraft-new
  annotations:
    nfs.io/storage-path: "minecraft"
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

