# a fresh new server that alex wanted
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-claim-new-local
  namespace: minecraft-new
  annotations:
    nfs.io/storage-path: "minecraft"
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

