---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
  namespace: minecraft-new
spec:
  loadBalancerIP: 192.168.150.11
  ports:
  - port: 25565
    targetPort: 25565
  selector:
    app: minecraft
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-deploy
  namespace: minecraft-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server
        volumeMounts:
        - name: minecraft-volume
          mountPath: "/data"
        ports:
        - containerPort: 25565
        env:
        - name: EULA
          value: "TRUE"
        - name: MEMORY
          value: "8G"
      volumes:
      - name: minecraft-volume
        persistentVolumeClaim:
          claimName: minecraft-claim-new

