apiVersion: batch/v1
kind: CronJob
metadata:
  name: ip-monitor-job
  namespace: ip-monitor
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: ip-monitor
            image: gammons1/ip-monitor:1
            imagePullPolicy: Always
            env:
              - name: AWS_DEFAULT_REGION
                value: "us-east-2"
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: s3-creds
                    key: aws-access-key-id
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: s3-creds
                    key: aws-secret-access-key
            command:
            - 'ruby'
            - 'ip_monitor.rb'
