apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: letsencrypt-prod
 namespace: default
spec:
 acme:
   email: grant@grant.dev
   privateKeySecretRef:
     name: letsencrypt-prod-key
   server: https://acme-v02.api.letsencrypt.org/directory
   solvers:
   - http01:
       ingress:
         class: nginx
